server:
   port: 8081

spring:
   security:
      oauth2:
         resourceserver:
            jwt:
               issuer-uri: http://localhost:8080/auth/realms/xrp
---
xrp:
   net:
      host: https://s.devnet.rippletest.net
      port: 51234
   faucet:
      host: https://faucet.devnet.rippletest.net
      port: 443
---
logging:
   level:
      root: INFO
      io.forest: DEBUG